require('core.options')
require('core.packer')
require('core.keymaps')

require('plugins.nvim-treesitter')
require('plugins.nvim-telescope')
require('plugins.nvim-tree')
require('plugins.nvim-cmp')
require('plugins.lsp.mason')
require('plugins.lualine')
require('plugins.gitsigns')
require('plugins.autopairs')
require('plugins.lsp.lspsaga')
require('plugins.lsp.lspconfig')
require('plugins.lsp.null-ls')
